spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 911106
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update