public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJByPOq72/iFQwaI+UnygK8HwVBHdkKM1j44pIR2UhiEA9X6O78tB4LvnWFOP6xnJ6SjuGnE+CORtTkS2AfeRr8CAwEAAQ==
spring:
  datasource:
    druid:
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
      filter:
        config:
          enabled: true
      filters: conn,config,stat,slf4j
      initial-size: 5
      max-active: 5
      min-idle: 5
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
    password: dnoZ2afntsyt7tGwApQwfY7SYpbEjnzKw99XryyzBwrcbQGU6Rsgjf3M7Y7F+phwT13/UXGYF5ephEjH1D/HNA==
    url: jdbc:mysql://localhost:3306/test
    username: root
  output:
    ansi:
      enabled: ALWAYS

